### ISSUE TITLE
Depreciated Functionality: strpos(): Passing null to parameter #1 ($haystack) of type string is depreciated

### ISSUE THREAD

**Issue by ecrocombe** [imagekit-developer/imagekit-magento#9]
**Preconditions and environment:**
Magento 2.4.5-p1
PHP 8.1.2-1ubuntu2.9
imagekit/imagekit 1.2.2
imagekit/imagekit-magento 1.0.4

**Steps to reproduce:**

1. Login to admin panel
2. Click Catalog >> Products

**Expected result**
Display a table of products.

**Actual result**
Error message displayed instead of table.

![Untitled](https://user-images.githubusercontent.com/42088209/205929375-d3a757f4-ec53-4300-aad3-ba57390d042f.png)

**Additional information**
Issue appears to originate from the [imagekit/imagekit v1.2.2 (SDK)](https://github.com/imagekit-developer/imagekit-php/blob/7102c2ecf62624c57e07ec82be763b3799815e8c/src/ImageKit/Url/Url.php#L197) and not the Magento Module (imagekit/imagekit-magento). 
It looks like this is fixed in more recent versions of imagekit/imagekit (v3), however imagekit/imagekit-magento's composer requires 1.2.2 of imagekit/imagekit.

For those finding this via search, I was able to temp fix this by modifying line 197 of <MAGENTO_ROOT>/vendor/imagekit/imagekit/src/ImageKit/Url/Url.php
FROM
```
if (strpos($value, '/') !== false) {
    $finalres .= str_replace('/', '@@', $value);
} else {
    $finalres .= $value;
}
```
TO
```
if (is_string($value) && strlen($value) > 0 && strpos($value, '/') !== false) {
    $finalres .= str_replace('/', '@@', $value);
} else {
    $finalres .= $value;
}
```
**WARNING:** The above temporary solution is thoroughly untested, use at your own risk.

**Comment by hans2103** [comment]
I can reproduce the issue. 
Using the provided code I was able to fix it on one of my shops. 
@imagekitio can you update your Magento plugin?
